name: Build
on: [ push, pull_request, merge_group ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21'
      - uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew clean build publishToMavenLocal --stacktrace
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Maven Local
          path: ~/.m2/repository
