name: Release

on:
  workflow_dispatch: 
    inputs: 
      release_type:
        description: 'The published artifact release type'
        required: false
        default: 'STABLE'
        type: choice
        options:
          - STABLE
          - BETA
          - ALPHA

permissions:
  actions: read
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FabricMC/fabric-action-scripts@v2
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21'
      - uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: false # Temporarily disabled
          gradle-home-cache-excludes: |
            gradle.properties
      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace
  publish:
    strategy:
      matrix:
        include:
          - name: Maven
            task: publish
            url: https://maven.su5ed.dev/releases/dev/su5ed/sinytra/Connector
          - name: GitHub
            task: publishGithub
            url: https://github.com/Sinytra/Connector/releases
          - name: CurseForge
            task: publishCurseforge
            url: https://www.curseforge.com/minecraft/mc-mods/sinytra-connector
          - name: Modrinth
            task: publishModrinth
            url: https://modrinth.com/mod/connector
    name: Publish ${{ matrix.name }}
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: ${{ matrix.name }}
      url: ${{ matrix.url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21'
      - uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true
          gradle-home-cache-cleanup: true
          gradle-home-cache-excludes: |
            gradle.properties
      - name: Publish with Gradle
        run: ./gradlew clean build ${{ matrix.task }} --stacktrace
        env:
          PUBLISH_RELEASE_TYPE: ${{ inputs.release_type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          CHANGELOG: ${{ needs.build.outputs.changelog }}
